### ISSUE TITLE
Deadlock: Session always polls for write readiness, never read readiness

### ISSUE THREAD

**Issue by emesterhazy** [bk-rs/ssh-rs#10]
# The Problem
`Async::write_with` is used throughout the codebase, but the corresponding `Async::read_with` function does not appear anywhere in this library. I don't think that it is safe to assume that the underlying `libssh2` session is always blocked on write readiness. `libssh2` and the `ssh2` Rust wrapper provide a [method](https://docs.rs/ssh2/0.9.1/ssh2/struct.Session.html#method.block_directions) to discover which direction the session is blocked on. `async-ssh2-lite` should use this to discover the direction (read, write, or both) and wait on readiness accordingly.

As is, I suspect that `AsyncSesson` spin and continuously call `ssh2` in cases where the session is write ready but not read ready and is blocked on read. Alternatively, we may deadlock if we're blocked on read and write readiness, and writing does not become unblocked until a read is performed. I'm not sure if this will happen in practice, but it seems possible theoretically.

In any case, the current implementation is inefficient at best, and incorrect at worst.

# A Solution
`AsyncSession` should call `Session::block_directions` to figure out which direction `libssh2` is blocked on and wait for readiness accordingly.

**Comment by vkill** [comment]
@emesterhazy

Thank you, you are right, this is a [sample](https://github.com/khvzak/async-ssh2-tokio/blob/master/src/io.rs#L52-L76) solution, I will fix it later.

**Comment by vkill** [comment]
v0.3.0 resolved
