### ISSUE TITLE
channel_session blocked

### ISSUE THREAD

**Issue by kolapapa** [bk-rs/ssh-rs#15]
When the `ssh server` is disconnected for some reason, `channel_session().await` will be blocked until the entire TCP connection is reset, and can't terminate even with `tokio::time::timeout`.

**Comment by vkill** [comment]
Hi, @kolapapa 
Please provide an example. Thank you.

**Comment by kolapapa** [comment]
> Hi, @kolapapa Please provide an example. Thank you.

I switched to the latest `0.3` version and it seems that the problem no longer reproduces...😅
