### ISSUE TITLE
sftp readdir method have some bug.

### ISSUE THREAD

**Issue by llvvrui** [bk-rs/ssh-rs#19]
In mac or k8s this readdir method wait infinitely,in fedora is all right.
```
        let mut session =
            AsyncSession::<TokioTcpStream>::connect(SocketAddr::from((host, port)), None).await?;
        session.handshake().await?;
        session
            .userauth_password(&config.user, &config.passwd)
            .await?;

        let stream = session.sftp().await?;

        stream.readdir(&Path::new(path)).await?
```rust

**Comment by vkill** [comment]
Oh, I only tested in Linux. you can try synchronous ssh2.

**Comment by vkill** [comment]
Or try using the async-io feature.

**Comment by llvvrui** [comment]
async-io is not ok! I find ssh2-rs library have a bug. LIBSSH2_ERROR_EAGAIN is not error. but it is used as error!

**Comment by vkill** [comment]
Hi @llvvrui  Please try https://github.com/bk-rs/ssh-rs/pull/20

**Comment by vkill** [comment]
https://github.com/bk-rs/ssh-rs/pull/21
