### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by priexp** [bk-rs/ssh-rs#2]
Hi,
version 0.1.3 does not compile under Windows(rustc v1.45.2, stable-x86_64-pc-windows-msvc toolchain).  Compiler is complaining about trait FromRawSocket is not in scope and sugests to import std::os::windows::prelude::FromRawSocket.
Greetings.

[fix_windows_compilation.zip](https://github.com/bk-rs/async-ssh2-lite/files/5125645/fix_windows_compilation.zip)

**Comment by vkill** [comment]
Sorry for the late reply, this is my mistake, Actually I did not build and test on window. Thanks again for your [PR](https://github.com/bk-rs/async-ssh2-lite/pull/3).

**Comment by vkill** [comment]
#3
