### ISSUE TITLE
v0.4.0 cannot compile on windows

### ISSUE THREAD

**Issue by yorkz1994** [bk-rs/ssh-rs#26]
Checking async-ssh2-lite v0.4.0
...

error[E0277]: the trait bound `u64: AsRawSocket` is not satisfied
   --> async-ssh2-lite\src\agent.rs:47:32
    |
47  |         session.set_tcp_stream(stream.as_raw_socket());
    |                 -------------- ^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRawSocket` is not implemented for `u64`

**Comment by vkill** [comment]
@yorkz1994 Please provide the complete usage code.

**Comment by yorkz1994** [comment]
Steps to reproduce the compiling error.

On windows system, just git clone and cargo check it, you will see the error. Rust 1.65 is used.

D:\tmp>git clone https://github.com/bk-rs/ssh-rs.git
Cloning into 'ssh-rs'...
remote: Enumerating objects: 764, done.
remote: Counting objects: 100% (231/231), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 764 (delta 179), reused 167 (delta 136), pack-reused 533
Receiving objects: 100% (764/764), 135.94 KiB | 597.00 KiB/s, done.
Resolving deltas: 100% (478/478), done.

D:\tmp>cd ssh-rs

D:\tmp\ssh-rs>cargo check
    Updating crates.io index
  Downloaded cc v1.0.78
  Downloaded 1 crate (61.4 KB) in 1.20s
   Compiling cc v1.0.78
   Compiling libz-sys v1.1.8
   Compiling wepoll-ffi v0.1.2
   Compiling libssh2-sys v0.2.23
    Checking polling v2.5.2
    Checking async-io v1.12.0
    Checking ssh2 v0.9.3
    Checking async-ssh2-lite v0.4.0 (D:\tmp\ssh-rs\async-ssh2-lite)
warning: unused import: `path::Path`
 --> async-ssh2-lite\src\util.rs:4:5
  |
4 |     path::Path,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0277]: the trait bound `u64: AsRawSocket` is not satisfied
   --> async-ssh2-lite\src\agent.rs:47:32
    |
47  |         session.set_tcp_stream(stream.as_raw_socket());
    |                 -------------- ^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRawSocket` is not implemented for `u64`
    |                 |
    |                 required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsRawSocket`:
              Async<T>
              BorrowedSocket<'_>
              OwnedSocket
              TcpListener
              TcpStream
              UdpSocket
              socket2::socket::Socket
              ssh2::Session
              std::sys::windows::net::Socket
note: required by a bound in `ssh2::Session::set_tcp_stream`
   --> C:\Users\york\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.9.3\src\session.rs:321:40
    |
321 |     pub fn set_tcp_stream<S: 'static + AsRawSocket>(&mut self, stream: S) {
    |                                        ^^^^^^^^^^^ required by this bound in `ssh2::Session::set_tcp_stream`

error[E0277]: the trait bound `u64: AsRawSocket` is not satisfied
   --> async-ssh2-lite\src\session.rs:65:32
    |
65  |         session.set_tcp_stream(stream.as_raw_socket());
    |                 -------------- ^^^^^^^^^^^^^^^^^^^^^^ the trait `AsRawSocket` is not implemented for `u64`
    |                 |
    |                 required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsRawSocket`:
              Async<T>
              BorrowedSocket<'_>
              OwnedSocket
              TcpListener
              TcpStream
              UdpSocket
              socket2::socket::Socket
              ssh2::Session
              std::sys::windows::net::Socket
note: required by a bound in `ssh2::Session::set_tcp_stream`
   --> C:\Users\york\.cargo\registry\src\github.com-1ecc6299db9ec823\ssh2-0.9.3\src\session.rs:321:40
    |
321 |     pub fn set_tcp_stream<S: 'static + AsRawSocket>(&mut self, stream: S) {
    |                                        ^^^^^^^^^^^ required by this bound in `ssh2::Session::set_tcp_stream`

For more information about this error, try `rustc --explain E0277`.
warning: `async-ssh2-lite` (lib) generated 1 warning
error: could not compile `async-ssh2-lite` due to 2 previous errors; 1 warning emitted

D:\tmp\ssh-rs>

**Comment by vkill** [comment]
Sorry, I don't have window here.

From The [doc](https://docs.rs/ssh2/latest/ssh2/struct.Session.html#method.set_tcp_stream) , AsRawSocket is correct, but AsRawSocket not impl AsRawFd , you can try the ssh2 crate directly, maybe should submit a PR to ssh2.

**Comment by vkill** [comment]
@yorkz1994 
Sorry, I don't have window here.
Please try edit `session.set_tcp_stream(stream.as_raw_socket());` to `session.set_tcp_stream(stream);`

**Comment by yorkz1994** [comment]
I changed it in two places, but the error is different now.

D:\tmp\ssh-rs>cargo check
    Checking async-ssh2-lite v0.4.0 (D:\tmp\ssh-rs\async-ssh2-lite)
warning: unused import: `path::Path`
 --> async-ssh2-lite\src\util.rs:4:5
  |
4 |     path::Path,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0382]: use of moved value: `stream`
  --> async-ssh2-lite\src\agent.rs:49:31
   |
45 |     pub fn new(stream: S) -> Result<Self, Error> {
   |                ------ move occurs because `stream` has type `S`, which does not implement the `Copy` trait
46 |         let mut session = get_session(None)?;
47 |         session.set_tcp_stream(stream);
   |                                ------ value moved here
48 |
49 |         let stream = Arc::new(stream);
   |                               ^^^^^^ value used here after move

error[E0382]: use of moved value: `stream`
  --> async-ssh2-lite\src\session.rs:67:31
   |
61 |         stream: S,
   |         ------ move occurs because `stream` has type `S`, which does not implement the `Copy` trait
...
65 |         session.set_tcp_stream(stream);
   |                                ------ value moved here
66 |
67 |         let stream = Arc::new(stream);
   |                               ^^^^^^ value used here after move

For more information about this error, try `rustc --explain E0382`.
warning: `async-ssh2-lite` (lib) generated 1 warning
error: could not compile `async-ssh2-lite` due to 2 previous errors; 1 warning emitted

D:\tmp\ssh-rs>

**Comment by vkill** [comment]
@yorkz1994 Please try https://github.com/bk-rs/ssh-rs/tree/fix-windows

**Comment by yorkz1994** [comment]
No compiling error now, just a warning.

D:\tmp\ssh-rs>cargo check
warning: unused import: `path::Path`
 --> async-ssh2-lite\src\util.rs:4:5
  |
4 |     path::Path,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `async-ssh2-lite` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s

**Comment by vkill** [comment]
Fixed in 0.4.1
