### ISSUE TITLE
Safety: Underlying FD for TCP connection is closed twice

### ISSUE THREAD

**Issue by emesterhazy** [bk-rs/ssh-rs#9]
# The Problem
https://github.com/bk-rs/async-ssh2-lite/blob/1b88c9cb64553ab395596a4368fc30e8e2e341c4/src/session.rs#L22-L44

From the `FromRawFd` [docs](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html):
> This function consumes ownership of the specified file descriptor. The returned object will take responsibility for closing it when the object goes out of scope.

The [docs](https://docs.rs/ssh2/0.9.1/ssh2/struct.Session.html#method.set_tcp_stream) for `ssh2::Session::set_tcp_stream` read:
> The session takes ownership of the stream provided.

If you look at the `Drop` for `SessionInner` it's clear that ssh2 isn't doing anything to prevent the `stream` passed to `set_tcp_stream` from being dropped.

As a result, I strongly suspect the underlying FD is being closed twice: once by the `Session` and once by the `Arc<Arync<S>>` members. This is BAD since the FD could be re-used elsewhere in the program between the first and second underlying call to `close()`, causing the FD to be closed out from under a type that believes it has exclusive ownership over the FD.

# A Solution
I think the solution is pretty simple. Instead of calling `session.set_tcp_stream(stream.into_inner()?)`, call `session.set_tcp_stream(stream.as_raw_fd())` and then wrap the original stream in an `Arc`. This way, `Session` doesn't own the FD and won't close it when it is dropped. This is fine since the `Session` doesn't actually need ownership of the FD as long as you ensure the FD outlives `Session`.

Note that this relies on the current ordering of the `AsyncSession<S>` members since [RFC 1857](https://rust-lang.github.io/rfcs/1857-stabilize-drop-order.html) ensures members are dropped from top to bottom (and we need to drop `async_io` last).
```rust
pub struct AsyncSession<S> {
    inner: Session,
    async_io: Arc<Async<S>>,
}
```

Here's what the code might look like:

```rust
#[cfg(unix)]
impl<S> AsyncSession<S>
where
    S: AsRawFd + FromRawFd + 'static,
{
    pub fn new(stream: Async<S>, configuration: Option<SessionConfiguration>) -> io::Result<Self> {
        let mut session = get_session(configuration)?;
        session.set_tcp_stream(stream.as_raw_fd());

        let async_io = Arc::new(stream);

        Ok(Self {
            inner: session,
            async_io,
        })
    }
}
```

Interested to hear your thoughts.

**Comment by vkill** [comment]
v0.3.0 resolved
